import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const facts=JSON.parse(await fs.readFile(path.join(root,'src/facts.json'),'utf8'));
const money=n=>n.toLocaleString('en-US');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const getStarted=`uv tool install 'harbor==0.18.0'\ngit clone https://github.com/GaugeForge/Quantum-Harbor\ncd Quantum-Harbor\ngit checkout ${facts.technical.repoCommit}\nuv sync\ndocker build -t qiqcbench-agent docker/agent/\nuv run python tools/build_qsim_images.py --tasks time_budgeted_hamlearn_10q\nharbor run -p harbor_tasks/time_budgeted_hamlearn_10q -a nop\nharbor view jobs`;
const navItems=[['overview','Overview'],['how-it-works','How It Works'],['timeline','Timeline'],['rules','Rules'],['getting-started','Getting Started'],['partners','Partners'],['faq','FAQ']];
const email=(subject)=>`mailto:${facts.contact}?subject=${encodeURIComponent(subject)}`;
const arrow='<img class="icon" src="assets/arrow-up-right.svg" alt="">';
const faqs=[
 ['Who can enter?','Individuals and teams of up to three people. There is no academic or professional qualification requirement. Applicable law and valid consent still apply.'],
 ['What exactly am I building?','An agent harness: the code that plans work, invokes tools, manages experiment state and verifies results around a fixed HY4 model. You may modify an existing harness or build your own.'],
 ['Is registration open?','The registration form is to be announced. Use the participation email link to ask the organizer for information. An email inquiry does not register a team.'],
 ['Are model credits unlimited?','Development allowance is to be announced. Tencent is a prospective provider; an unlimited-credit arrangement is not confirmed. Each team has at most three official full benchmark evaluations.'],
 ['How is the Challenger Award different?','USD 15,000 goes only to the first qualifying HY4 team to strictly exceed the GPT-6 Astra baseline on the hidden leaderboard. Timestamp, baseline and stacking details will be frozen before registration. Placement awards follow the expert final.'],
 ['Are hidden tasks guaranteed uncontaminated?','No. Public paper tasks and repository material are already accessible. Hidden means withheld during evaluation, not proven absent from training data. Evaluation uses recorded evidence and controlled conditions.'],
 ['Do I need quantum hardware?','No. Quantum-Harbor provides a simulated laboratory. Real-hardware access is not part of the announced competition.'],
 ['What must I open source?','Submitted harness code is required to be AGPL open source. The exact version and release timing will be frozen before registration. Data and trajectory use has separate terms, including named organizer and partner recipients.'],
 ['Where are submissions uploaded?','The event submission interface is not yet released. The public repository supports local task runs. The participant guide labels the proposed competition package separately.']
];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Build an agent harness around HY4 for verified quantum engineering. QIQC Challenge by GaugeForge starts ${facts.schedule.start.label}."><meta name="theme-color" content="#f5f7f8"><title>QIQC Challenge | GaugeForge</title><link rel="stylesheet" href="styles.css"></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation" title="Open navigation"><img src="assets/menu.svg" alt=""></button><nav id="navigation" aria-label="Main navigation">${navItems.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></header>
<main id="main"><section class="hero" id="overview"><div class="hero-copy wrap"><p class="eyebrow">QIQC CHALLENGE / GLOBAL · ONLINE</p><h1>Agentic Quantum<br>Coding Challenge</h1><p class="lead"><strong>${facts.messaging.hook}</strong><br>${facts.messaging.support}<br><strong>Challenger Award: USD ${money(facts.prizes.challengerAmount)}.</strong></p><div class="actions"><a class="button primary" href="${email('QIQC Challenge participation inquiry')}">Contact to participate ${arrow}</a><a class="text-link" href="#getting-started">Start building <img class="icon" src="assets/arrow-right.svg" alt=""></a></div><p class="small">Registration link: To be announced</p></div><figure class="hero-visual"><img src="assets/rabi-calibration.webp" alt="Analytical Rabi calibration map of excitation probability versus pulse duration and detuning"><figcaption>Rabi calibration / analytical illustration, not benchmark results</figcaption></figure></section>
<section class="event-strip"><div class="wrap strip-grid"><div><span>STARTS</span><strong>${facts.schedule.start.label}</strong></div><div><span>TEAM SIZE</span><strong>${facts.rules.teamMin}–${facts.rules.teamMax} people</strong></div><div><span>FIXED MODEL</span><strong>${facts.model.label}</strong></div><div><span>OFFICIAL EVALUATIONS</span><strong>${facts.rules.maxFullEvaluations} per team</strong></div></div></section>
<section class="section wrap" id="how-it-works"><div class="section-heading"><p class="eyebrow">01 / THE CHALLENGE</p><h2>The engineering is in the harness.</h2><p>Choose the next experiment. Interpret the measurement. Recover when a plan fails. Quantum-Harbor makes the result inspectable.</p></div><ol class="steps"><li><span>01</span><h3>Build</h3><p>Design the planning, memory and tool orchestration around a shared HY4 model.</p></li><li><span>02</span><h3>Experiment</h3><p>Practice on five released tasks in a virtual quantum laboratory with real resource constraints.</p></li><li><span>03</span><h3>Verify</h3><p>Submit your harness for complete evaluations. The automated ranking selects five finalists.</p></li><li><span>04</span><h3>Explain</h3><p>Show one success and one failure. Experts decide the finalists' award order.</p></li></ol><div class="research-line"><p>Built on <strong>QIQCBench + Quantum-Harbor</strong>. The research spans calibration, control, error correction, compilation, simulation and sensing.</p><a href="${facts.links.paper}">Read the paper ${arrow}</a><a href="${facts.links.benchmark}">Explore the benchmark ${arrow}</a></div></section>
<section class="awards-band"><div class="wrap awards-grid"><div><p class="eyebrow">THE CHALLENGER AWARD</p><h2>USD ${money(facts.prizes.challengerAmount)}</h2><p>Only the first qualifying HY4 team to strictly beat the <strong>GPT-6 Astra hidden leaderboard baseline</strong>.</p><p class="small">Timestamp, baseline and prize-stacking details: To be announced.</p></div><div><h3>Finalist awards</h3><dl class="prize-list">${facts.prizes.places.map((v,i)=>`<div><dt>${['Champion','Second','Third','Fourth','Fifth'][i]}</dt><dd>USD ${money(v)}</dd></div>`).join('')}</dl><p class="small">Finalist order is determined by expert review. Payment terms will be published before registration.</p></div></div></section>
<section class="section wrap" id="timeline"><div class="section-heading"><p class="eyebrow">02 / TIMELINE</p><h2>Make room to build.</h2><p>The competition begins on ${facts.schedule.start.label}. Remaining dates will be announced together with the complete rules.</p></div><div class="timeline"><div><span>Registration & preparation</span><strong>To be announced</strong></div><div class="confirmed"><span>Competition begins</span><strong>${facts.schedule.start.label}</strong></div><div><span>Submission deadline</span><strong>To be announced</strong></div><div><span>Final review & Demo Day</span><strong>To be announced</strong></div></div><p class="small">Published event times will use UTC+8. Start time is to be announced.</p></section>
<section class="section rules-section" id="rules"><div class="wrap"><div class="section-heading"><p class="eyebrow">03 / RULES</p><h2>A common model. Comparable evidence.</h2></div><div class="rules-grid"><div><h3>Confirmed conditions</h3><ul><li>1–3 people per team; no academic or professional eligibility restriction.</li><li>HY4 for official model inference.</li><li>At most three complete official benchmark evaluations per team.</li><li>Submitted harness code must be AGPL open source.</li><li>Organizer and participating partners have data and execution-trajectory usage rights under disclosed terms.</li></ul></div><div><h3>Evaluation protocol</h3><p>The public board shows five public tasks. Hidden results are withheld until final evaluation. The proposed automated total gives every task equal weight after normalization to [0,1].</p><p>The top five eligible, reproducible entries advance. Experts decide the order among those five; the automated leaderboard stays separately visible.</p><p class="small">Detailed scoring, ties, rights, resource limits and appeal windows are proposed until the rule freeze. Public material is not claimed to be uncontaminated.</p></div></div><a class="button secondary" href="downloads/participant-guide.pdf"><img class="icon" src="assets/download.svg" alt=""> Participant guide PDF</a><a class="text-link" href="downloads/participant-guide.html">Read the full guide ${arrow}</a></div></section>
<section class="section wrap" id="getting-started"><div class="section-heading"><p class="eyebrow">04 / GETTING STARTED</p><h2>Run the public lab.</h2><p>Docker, uv, git and Python 3.11+. On Windows, use Linux containers through WSL2. The no-key check below tests the public environment.</p></div><div class="terminal"><div class="terminal-bar"><span>Quantum-Harbor / Harbor 0.18.0</span><button id="copy-code" title="Copy installation commands" aria-label="Copy installation commands"><img src="assets/copy.svg" alt=""></button></div><pre><code id="install-code">${esc(getStarted)}</code></pre></div><p id="copy-status" role="status" class="small"></p><p class="note"><strong>Expected result: reward 0.</strong> The <code>nop</code> agent performs no science. This is an installation check, not an official entry.</p><p>The public repository includes example agent configurations. The competition HY4 starter adapter, model ID and upload service are to be announced. The current examples must not be presented as a working HY4 integration.</p><div class="actions"><a class="button secondary" href="${facts.links.repository}">Open Quantum-Harbor ${arrow}</a><a class="text-link" href="${facts.links.repository}/blob/${facts.technical.repoCommit}/docs/getting-started/installation.md">Installation reference ${arrow}</a></div></section>
<section class="section partners-section" id="partners"><div class="wrap"><p class="eyebrow">05 / PARTNERS</p><h2>Bring your community or expertise.</h2><div class="partner-content"><p>Hosted by <strong>GaugeForge</strong>. Community distribution, expert review, model support and post-event experiments are available ways to contribute.</p><p>External partners will be announced after confirmation. No external organization is currently listed as a confirmed event partner.</p></div><div class="actions"><a class="button primary" href="${email('QIQC Challenge partnership inquiry')}">Discuss a partnership ${arrow}</a><a class="text-link" href="downloads/partner-handbook.pdf">Partner handbook PDF <img class="icon" src="assets/download.svg" alt=""></a></div></div></section>
<section class="section wrap" id="faq"><div class="section-heading"><p class="eyebrow">06 / FAQ</p><h2>Before you enter.</h2></div><div class="faq">${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
<section class="participate-band"><div class="wrap"><p class="eyebrow">BUILD SOMETHING VERIFIABLE</p><h2>Join the QIQC Challenge.</h2><p>Starts ${facts.schedule.start.label}. Registration link: To be announced.</p><a class="button primary" href="${email('QIQC Challenge participation inquiry')}">Contact to participate ${arrow}</a><a class="contact" href="mailto:${facts.contact}">${facts.contact}</a><p class="small">Email inquiry only. Your mail application opens; nothing is sent automatically.</p></div></section></main>
<footer class="site-footer wrap"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><p>QIQC Challenge / ${facts.version}</p><p>No registration data is collected on this site. Inquiries are handled by GaugeForge.<br>Data rights and the final participant privacy notice will be available before registration.</p><a href="downloads/participant-guide.html">Privacy and participant terms</a></footer><script src="app.js" defer></script></body></html>`;
await fs.writeFile(path.join(root,'src/index.html'),html);
await fs.writeFile(path.join(root,'src/404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found | QIQC</title><h1>Page not found</h1><a href="/">Return to QIQC Challenge</a></html>');
await fs.writeFile(path.join(root,'src/_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src \'self\'; img-src \'self\' data:; style-src \'self\' \'unsafe-inline\'; script-src \'self\'; object-src \'none\'; base-uri \'self\'; form-action \'none\'\n');
