import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const facts=JSON.parse(await fs.readFile(path.join(root,'src/facts.json'),'utf8'));
const money=n=>n.toLocaleString('en-US');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const getStarted=`uv tool install 'harbor==0.18.0'\ngit clone https://github.com/GaugeForge/Quantum-Harbor\ncd Quantum-Harbor\ngit checkout ${facts.technical.repoCommit}\nuv sync\ndocker build -t qiqcbench-agent docker/agent/\nuv run python tools/build_qsim_images.py --tasks time_budgeted_hamlearn_10q\nharbor run -p harbor_tasks/time_budgeted_hamlearn_10q -a nop\nharbor view jobs`;
const navItems=[['task','Task'],['evaluation','Evaluation'],['getting-started','Build'],['faq','FAQ']];
const email=(subject)=>`mailto:${facts.contact}?subject=${encodeURIComponent(subject)}`;
const svgIcon=async name=>(await fs.readFile(path.join(root,'src/assets',name+'.svg'),'utf8')).replace(/<!--[\s\S]*?-->/g,'').replace(/class="[^"]*"/,'').replace('<svg','<svg class="icon" aria-hidden="true" focusable="false"').replace(/>\s+</g,'><').replace(/\s*\n\s*/g,' ').trim();
const arrow=await svgIcon('arrow-up-right');
const arrowRight=await svgIcon('arrow-right');
const faqs=[
 ['Who can enter?','Individuals and teams of up to three people. There is no academic or professional qualification requirement. Applicable law and valid consent still apply.'],
 ['What exactly am I building?','An agent harness: the code that plans work, invokes tools, manages experiment state and verifies results around a fixed Hunyuan 4 Preview (HY4) model. You may modify an existing harness or build your own.'],
 ['Is registration open?','The registration form is to be announced. Use the participation email link to ask the organizer for information. An email inquiry does not register a team.'],
 ['Are model credits unlimited?','The event model is Tencent Hunyuan 4 Preview (HY4). Exact API quota and development allowance are to be announced. Each team has at most three official full benchmark evaluations.'],
 ['How is the Challenger Award different?','USD 15,000 goes only to the strict first qualifying Hunyuan 4 Preview (HY4) team to exceed the GPT-6 Astra baseline on the hidden leaderboard. If no team exceeds it, the award is not paid. Timestamp, baseline and stacking details will be frozen before registration.'],
 ['Are hidden tasks guaranteed uncontaminated?','No. Public paper tasks and repository material are already accessible. Hidden means withheld during evaluation, not proven absent from training data. Evaluation uses recorded evidence and controlled conditions.'],
 ['Do I need quantum hardware?','No. Quantum-Harbor provides a simulated laboratory. Real-hardware access is not part of the announced competition.'],
 ['What must I open source?','Submitted harness code is required to be AGPL open source. The exact version and release timing will be frozen before registration. Data and trajectory use has separate terms, including named organizer and partner recipients.'],
 ['Where are submissions uploaded?','The event submission interface is not yet released. The public repository supports local task runs. The participant guide labels the proposed competition package separately.']
];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Build an agent harness around Hunyuan 4 Preview for verified quantum engineering. QIQC Challenge by GaugeForge starts ${facts.schedule.start.label}."><meta name="theme-color" content="#f5f7f8"><title>QIQC Challenge | GaugeForge</title><link rel="stylesheet" href="styles.css"></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation" title="Open navigation"><img src="assets/menu.svg" alt=""></button><nav id="navigation" aria-label="Main navigation">${navItems.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></header>
<main id="main">
<section class="hero-stage" id="overview" aria-labelledby="hero-title"><div class="hero">
<div class="hero-field" id="rabi-lab" aria-hidden="true"><img class="field-fallback" src="assets/rabi-calibration.webp" alt=""><canvas id="rabi-canvas"></canvas></div>
<div class="field-caption protected" id="rabi-caption"><p>RABI OSCILLATIONS</p><span>Pulse duration × detuning · ideal two-level model</span><div><span>Illustration, not experimental data</span><button id="rabi-play" type="button" aria-label="Pause background animation">Ⅱ &nbsp; Pause motion</button></div></div>
<div class="hero-inner wrap">
<div class="hero-copy">
<h1 id="hero-title" class="protected"><span class="title-line"><span class="motion-surface">Agentic Quantum</span></span><br><span class="title-line"><span class="motion-surface"><em>Coding Challenge</em></span></span></h1>
<p class="event-intro protected"><span class="intro-line">An online challenge to build AI agents for quantum engineering.</span><span class="intro-line">Design your harness around Hunyuan 4 Preview and put it to the test.</span></p>
<p class="hero-slogan protected"><mark>${facts.messaging.hook}</mark></p>
</div>
<section class="entry-basics" aria-label="Participation essentials">
<div class="entry-details"><div class="entry-who"><span class="basic-label">WHO CAN JOIN</span><h3>Everyone. Solo or a team.</h3><p>${facts.rules.teamMin}–${facts.rules.teamMax} people per team. No academic or professional qualification required.</p></div><div class="entry-how"><span class="basic-label">HOW TO JOIN</span><h3>Form a team. Build your harness.</h3><p>Register, practice in the public lab, then submit your harness for evaluation.</p></div><div class="entry-register">${facts.links.registration?`<a class="button primary register-now" href="${facts.links.registration}">Register now ${arrow}</a>`:`<button class="button primary register-now" id="register-now" type="button" aria-haspopup="dialog">Register now ${arrow}</button>`}<span>${facts.links.registration?'Join the challenge.':'Registration form coming soon.'}</span><a class="button register-now rules-pdf" href="downloads/participant-guide.pdf" target="_blank" rel="noopener" aria-label="View Participant Guide (opens in a new tab)">View Participant Guide</a></div></div>
<div class="prize-overview"><article><span class="rule-label">PLACEMENT PRIZE POOL</span><h3 aria-label="USD ${money(facts.prizes.placesTotal)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.placesTotal}" style="--number-width:${money(facts.prizes.placesTotal).length}ch">${money(facts.prizes.placesTotal)}</span></span></h3><p>Total across the five placement awards.</p><div class="place-amounts">${facts.prizes.places.map((v,i)=>`<span><small>#${i+1}</small> $${money(v)}</span>`).join('')}</div></article><article class="challenger-prize"><span class="rule-label">THE CHALLENGER AWARD</span><h3 aria-label="USD ${money(facts.prizes.challengerAmount)}"><span aria-hidden="true">USD <span class="prize-number" data-amount="${facts.prizes.challengerAmount}" style="--number-width:${money(facts.prizes.challengerAmount).length}ch">${money(facts.prizes.challengerAmount)}</span></span></h3><p>Only the <strong>strict first team</strong> to exceed GPT-6 Astra on the hidden leaderboard.<br>If nobody exceeds it, the award is not paid.</p></article></div>
<div id="timeline" class="entry-timeline"><span class="basic-label">TIMELINE <small>2026 · UTC+8</small><small id="timeline-status" class="timeline-status">Date progress</small></span><div class="timeline-body"><div class="timeline-rail"><div class="timeline-progress" role="progressbar" aria-label="Progress from competition start to Demo Day" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-describedby="timeline-status" data-start="${facts.schedule.start.date}" data-deadline="${facts.schedule.deadline.date}" data-end="${facts.schedule.demo.date}"><span class="timeline-progress-fill"></span></div><span class="timeline-current" data-edge="start"><button class="timeline-status-dot" type="button" aria-label="Current timeline status" aria-describedby="timeline-tooltip"></button><span id="timeline-tooltip" class="timeline-tooltip" role="tooltip">The competition has not started yet.</span></span></div><ol>${[['start','Competition begins'],['deadline','Submission deadline'],['demo','Demo Day']].map(([key,label])=>`<li><span class="timeline-event">${label}</span><time datetime="${facts.schedule[key].date}">NOV ${facts.schedule[key].date.slice(-2)}</time></li>`).join('')}</ol></div></div>
</section>
</div>
</div></section>
<section class="section task-section" id="task" aria-labelledby="task-title"><div class="wrap">
<div class="section-heading heading-split"><h2 id="task-title" class="section-title">Task</h2></div>
<p class="task-goal">Every team uses the same <strong>Tencent Hunyuan 4 Preview (HY4)</strong> model. Your goal is to improve the <strong>harness</strong> around it: how the agent plans experiments, uses tools, learns from evidence and produces reliable solutions to quantum engineering tasks.</p>
<div class="task-layout">
<div class="task-copy"><h3>What your agent must do</h3><p>QIQCBench presents engineering problems in Quantum-Harbor, a simulated quantum laboratory. Your agent reads the task, chooses experiments within its resource budget, interprets the measurements and submits an answer that a separate verifier can check.</p>
<ul class="task-examples"><li><strong>Characterize a system.</strong> Estimate an unknown Hamiltonian or predict quantum correlations.</li><li><strong>Calibrate an experiment.</strong> Tune a controlled-Z pulse or a logical-CNOT decoder.</li><li><strong>Design measurements.</strong> Estimate molecular energy and its uncertainty.</li></ul>
<p class="task-deliverable">Each task defines its own tools, budget and answer format. Your competition entry is the harness that solves these tasks.</p>
<div class="task-split"><span><strong>${facts.rules.publicTasks}</strong> public practice tasks</span><span><strong>${facts.rules.eventTaskCount-facts.rules.publicTasks}</strong> hidden evaluation tasks</span></div>
</div>
<div class="task-interactive"><p class="task-step-hint">Explore a task, step by step.</p>
<div class="task-steps" role="tablist" aria-label="Task stages">${['Understand','Plan','Experiment','Verify'].map((name,i)=>`<button id="task-step-${i}" type="button" role="tab" data-task-step="${i}" aria-controls="task-panel" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}"><span class="task-step-number">${i+1}</span><span>${name}</span></button>`).join('')}</div>
<div id="task-panel" class="task-panel" role="tabpanel" aria-labelledby="task-step-0" tabindex="0" aria-live="polite" aria-atomic="true">
<h3 id="task-stage-title">Understand the objective.</h3><p id="task-stage-copy">Read the task instructions and device specifications. Identify the quantity to estimate or the operation to calibrate, the available tools and the limits on experiments.</p>
<div class="task-schematic" aria-hidden="true"><span id="task-node-a">Task brief</span>${arrowRight}<span id="task-node-b">Tools &amp; limits</span>${arrowRight}<span id="task-node-c">Success criteria</span></div>
<p id="task-stage-outcome" class="task-outcome">Start with a clear target and an experiment budget.</p>
</div><p class="task-demo-note">Illustrative workflow. No model call or experiment runs here.</p>
</div></div>
<div class="research-line"><p>Built on <strong>QIQCBench + Quantum-Harbor</strong>.</p><a href="${facts.links.paper}">Read the paper ${arrow}</a><a href="${facts.links.benchmark}">Explore the benchmark ${arrow}</a></div>
</div></section>
<section class="section evaluation-section" id="evaluation" aria-labelledby="evaluation-title"><div class="wrap">
<div class="section-heading"><h2 id="evaluation-title" class="section-title">Evaluation</h2><p class="evaluation-intro">Evaluation runs your submitted harness on the benchmark and checks its answers against recorded evidence. The rules define a valid run; the results show how the harness performed and how awards are decided.</p></div>
<div class="evaluation-columns">
<div class="evaluation-rules"><h3>Rules</h3><dl class="evaluation-list">
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-1"><span>A shared model and benchmark</span></label></dt><dd>All teams use Tencent Hunyuan 4 Preview (HY4). Each complete evaluation covers all ${facts.rules.eventTaskCount} QIQCBench tasks: ${facts.rules.publicTasks} public and ${facts.rules.eventTaskCount-facts.rules.publicTasks} hidden.</dd></div>
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-2"><span>Up to ${facts.rules.maxFullEvaluations} complete evaluations per team</span></label></dt><dd>One complete benchmark run counts as one evaluation. Local practice on public tasks is separate from the official allowance.</dd></div>
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-3"><span>An open, reproducible harness</span></label></dt><dd>Submit your harness under AGPL. Follow each task's tool limits, experiment budget and answer format, and retain the evidence needed to check the result.</dd></div>
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-4"><span>Evidence before claims</span></label></dt><dd>A separate verifier checks task outcomes using recorded or replayed evidence. A claimed success must be supported by what the agent actually did.</dd></div>
</dl></div>
<div class="evaluation-results"><h3>Results</h3><dl class="evaluation-list">
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-5"><span>Public feedback and hidden results</span></label></dt><dd>The public board reports performance on the ${facts.rules.publicTasks} public tasks. Hidden scores are released after the submission deadline and reproducibility checks, as described in the participant guide.</dd></div>
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-6"><span>Automated score and placement review <span class="protocol-note">Proposed</span></span></label></dt><dd>The proposed automated score averages all ${facts.rules.eventTaskCount} task scores, with equal weight per task. The top five eligible entries then advance to expert review to determine the placement awards.</dd></div>
<div><dt><label class="evaluation-check"><input type="checkbox" name="reviewed-item-7"><span>The Challenger Award</span></label></dt><dd>USD ${money(facts.prizes.challengerAmount)} goes only to the strict first qualifying HY4 team to exceed GPT-6 Astra on the hidden leaderboard. Matching the baseline or exceeding it later does not qualify. If nobody exceeds it, the award is not paid.</dd></div>
</dl><p class="evaluation-note">Detailed scoring, review and timestamp procedures remain subject to the final rule freeze. See the Participant Guide for the current protocol.</p></div>
</div></div></section>
<section class="section wrap" id="getting-started"><div class="section-heading"><h2 class="section-title">Build</h2><p>Docker, uv, git and Python 3.11+. On Windows, use Linux containers through WSL2. The no-key check below tests the public environment.</p></div><div class="terminal"><div class="terminal-bar"><span>Quantum-Harbor / Harbor 0.18.0</span><button id="copy-code" title="Copy installation commands" aria-label="Copy installation commands"><img src="assets/copy.svg" alt=""></button></div><pre><code id="install-code">${esc(getStarted)}</code></pre></div><p id="copy-status" role="status" class="small"></p><p class="note"><strong>Expected result: reward 0.</strong> The <code>nop</code> agent performs no science. This is an installation check, not an official entry.</p><p>The public repository includes example agent configurations. The competition Hunyuan 4 Preview adapter, exact model ID and upload service are to be announced. The current examples must not be presented as a working event integration.</p><div class="actions"><a class="button secondary" href="${facts.links.repository}">Open Quantum-Harbor ${arrow}</a><a class="text-link" href="${facts.links.repository}/blob/${facts.technical.repoCommit}/docs/getting-started/installation.md">Installation reference ${arrow}</a></div></section>
<section class="section partners-section" id="partners"><div class="wrap"><h2 class="section-title">Partners</h2><div class="partner-content"><p>Hosted by <strong>GaugeForge</strong>. Community distribution, expert review, model support and post-event experiments are available ways to contribute.</p><p>External partners will be announced after confirmation. No external organization is currently listed as a confirmed event partner.</p></div><div class="actions"><a class="button primary" href="${email('QIQC Challenge partnership inquiry')}">Discuss a partnership ${arrow}</a><a class="text-link" href="downloads/partner-handbook.pdf">Partner handbook PDF <img class="icon" src="assets/download.svg" alt=""></a></div></div></section>
<section class="section wrap" id="faq"><div class="section-heading"><h2 class="section-title">FAQ</h2></div><div class="faq">${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
<section class="participate-band" aria-labelledby="contact-title"><div class="wrap"><h2 id="contact-title">More questions? Email us.</h2><a class="contact" href="mailto:${facts.contact}">${facts.contact}</a><p class="small">Email inquiry only. Your mail application opens; nothing is sent automatically.</p></div></section></main>
${facts.links.registration?'':`<dialog id="registration-dialog" aria-labelledby="registration-title" aria-describedby="registration-description"><button type="button" class="dialog-close" aria-label="Close registration information">×</button><p class="eyebrow">QIQC CHALLENGE / REGISTRATION</p><h2 id="registration-title">Join the challenge.</h2><p id="registration-description">The official registration form is coming soon. Contact GaugeForge for participation information in the meantime.</p><a class="button primary" href="${email('QIQC Challenge registration inquiry')}">Contact the organizer ${arrow}</a><p class="dialog-note">An email inquiry does not register a team. Nothing is submitted automatically.</p></dialog>`}
<footer class="site-footer wrap"><a class="brand" href="#overview">GaugeForge<span aria-hidden="true">▍</span></a><p>QIQC Challenge / ${facts.version}</p><p>No registration data is collected on this site. Inquiries are handled by GaugeForge.<br>Data rights and the final participant privacy notice will be available before registration.</p><a href="downloads/participant-guide.html">Privacy and participant terms</a></footer><script src="app.js" defer></script></body></html>`;
await fs.writeFile(path.join(root,'src/index.html'),html);
await fs.writeFile(path.join(root,'src/404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found | QIQC</title><h1>Page not found</h1><a href="/">Return to QIQC Challenge</a></html>');
await fs.writeFile(path.join(root,'src/_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src \'self\'; img-src \'self\' data:; style-src \'self\' \'unsafe-inline\'; script-src \'self\'; object-src \'none\'; base-uri \'self\'; form-action \'none\'\n');
